version: '3.8'

volumes:
  db_data:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/ihama/data/database/.
      o: bind
      type: none

  wp_data:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/ihama/data/web/.
      o: bind
      type: none

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports: 
      - "443:443"
    volumes:
      - /home/ihama/data/web:/var/www/html
    networks:
      inception:

  wordpress:
    environment:
      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
      - WP_USER=${WP_USER}
      - WP_PASS=${WP_PASS}
      - WP_EMAIL=${WP_EMAIL}
      - W_USER1=${W_USER1}
      - W_UPASS=${W_UPASS}
      - W_UEMAIL=${W_UEMAIL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      inception:

  mariadb:
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      inception:

networks:
  inception:
